name: Omni M3U Generator

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Omni Generator Script
        run: python generate_omni.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add omni.m3u
          # Commit only if there are changes
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update omni.m3u playlist"
          git push
